# Generated by Django 4.2.5 on 2023-09-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email')),
                ('second_name', models.CharField(max_length=30, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
