# Generated by Django 4.2.5 on 2023-09-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')),
                ('status', models.CharField(verbose_name='статус попытки')),
                ('server_response', models.CharField(verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение рассылки',
                'verbose_name_plural': 'сообщения  рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(verbose_name='дата и время начала')),
                ('datetime_finish', models.DateTimeField(verbose_name='дата и время окончания')),
                ('schedule', models.CharField(choices=[('1D', 'Раз в день'), ('1W', 'Раз в неделю'), ('1M', 'Раз в месяц')], max_length=20, verbose_name='периодичность')),
                ('status', models.CharField(default='Создана', max_length=20, verbose_name='статус')),
                ('is_active', models.BooleanField(default=False, verbose_name='состояние скрипта')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailingmessage', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email')),
                ('second_name', models.CharField(max_length=30, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('mailings', models.ManyToManyField(to='main.mailing', verbose_name='рассылки')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
