# Generated by Django 4.2.5 on 2023-10-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mailing_is_sent_by_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='server_response',
            field=models.CharField(blank=True, null=True, verbose_name='ответ сервера'),
        ),
    ]
